# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ded643da85c096ea9b1ebf89d5ca4024de2534bad22804c996eb489624de70f6ce3f5202c01b0f55b5fa54a0b4760b409a4d859390fff1180a57f2726ff14a7

test:
  secret_key_base: a3a16138fb8bd988bf05be6c4079b8050055da0b09305ba4ce9cc51573c030e4d45555cb7f2c3030ce3a2b9265fc260cffb4c3f96744f7d8af974842b6368ea5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
